# This is a basic workflow to help you get started with Actions

name: TriggerOtherRepo

on:
  workflow_dispatch:
    inputs:
      target_module:
        description: 'Input a terraform module name (e.g., demo-app)'
        required: true
      target_version:
        description: 'Input a version (e.g., v1.0.0)'
        required: true

jobs:
  trigger:
    runs-on: ubuntu-latest
    
    steps:
      - name: Trigger Workflow in Another Repository
        run: |
          # Set the required variables
          repo_owner="T1ckL35" 
          repo_name="MyFirstAction"  
          event_type="trigger-workflow" 
          module="${{ github.event.inputs.target_module }}"
          version="${{ github.event.inputs.target_version }}"

          # Have set a Personal Access Token up (30 day expiry) with Read/Write access to Actions on this ("Contents" repository permissions (write)) and the FirstAction repository.
          # Added the value to a repository secret in this repo called PAT_TRIGGER_TESTS to use below
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.PAT_TRIGGER_TESTS }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/$repo_owner/$repo_name/dispatches \
            -d "{\"event_type\": \"$event_type\", \"client_payload\": {\"module\": \"$module\", \"version\": \"$version\", \"unit\": false, \"integration\": true}}"

# Controls when the workflow will run
#on:
#  # Triggers the workflow on push or pull request events but only for the "main" branch
#  push:
#    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]
#
#  # Allows you to run this workflow manually from the Actions tab
#  workflow_dispatch:
#
# # A workflow run is made up of one or more jobs that can run sequentially or in parallel
# jobs:
#   # This workflow contains a single job called "build"
#   build:
#     # The type of runner that the job will run on
#     runs-on: ubuntu-latest

#     # Steps represent a sequence of tasks that will be executed as part of the job
#     steps:
#       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
#       - uses: actions/checkout@v4

#       # Runs a single command using the runners shell
#       - name: Run a one-line script
#         run: echo Hello, world!

#       # Runs a set of commands using the runners shell
#       - name: Run a multi-line script
#         run: |
#           echo Add other actions to build,
#           echo test, and deploy your project.
